### ISSUE TITLE
Too much of a good thing: excessive undoes will break or crash cling

### ISSUE THREAD

**Issue by drvink** [vgvassilev/cling#130]
### cling will be the cause of its own undoing if your first transaction is an undo

```
arch-vm[1083]:~% cling --nologo
[cling]$ .stats undo
<cling::Transaction* 0x526e3d0 isEmpty=0 isCommitted=1>
`   <cling::Transaction* 0x542e140 isEmpty=0 isCommitted=1>
[cling]$ .undo
[cling]$ 1
#0 0x00000000009c6bd8 (cling+0x9c6bd8)
#1 0x00000000009c4b3e (cling+0x9c4b3e)
#2 0x00000000009c4c7a (cling+0x9c4c7a)
#3 0x00007fba8a8320b0 __restore_rt (/usr/lib/libc.so.6+0x330b0)
#4 0x00000000021fb27d (cling+0x21fb27d)
#5 0x00000000009606c3 (cling+0x9606c3)
#6 0x00000000009620e5 (cling+0x9620e5)
#7 0x00000000009625d6 (cling+0x9625d6)
#8 0x00000000008f8396 (cling+0x8f8396)
#9 0x00000000008f8474 (cling+0x8f8474)
#10 0x00000000008f85fd (cling+0x8f85fd)
#11 0x000000000093705d (cling+0x93705d)
#12 0x000000000093866c (cling+0x93866c)
#13 0x000000000093c35e (cling+0x93c35e)
#14 0x000000000093c737 (cling+0x93c737)
#15 0x000000000097d4ab (cling+0x97d4ab)
#16 0x00000000009d041f (cling+0x9d041f)
#17 0x00000000008844a0 (cling+0x8844a0)
#18 0x00007fba8a81f291 __libc_start_main (/usr/lib/libc.so.6+0x20291)
#19 0x00000000008b256a (cling+0x8b256a)
Stack dump:
0.      Program arguments: cling --nologo
zsh: segmentation fault (core dumped)  cling --nologo
```
<hr />

### cling is more than happy to unload parts of itself

```
arch-vm[1083]:~% cling --nologo
[cling]$ .stats undo
<cling::Transaction* 0x54993d0 isEmpty=0 isCommitted=1>
`   <cling::Transaction* 0x5659140 isEmpty=0 isCommitted=1>
[cling]$ 1
(int) 1
[cling]$ .undo 999
cling: invalid last transaction; unload failed!
[cling]$ .stats undo
```

The undo stack is completely empty! What happens if we try to evaluate something?

```
[cling]$ 1
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
```

Evaluation is broken at this point and you must restart cling.
<hr />

### Transactions are incorrectly grouped/counted with respect to undoes

Eval/undo-1 works forever:

```
arch-vm[1085]:~% cling --nologo
[cling]$ .stats undo
<cling::Transaction* 0x48503d0 isEmpty=0 isCommitted=1>
`   <cling::Transaction* 0x4a10140 isEmpty=0 isCommitted=1>
[cling]$ 1
(int) 1
[cling]$ .stats undo
<cling::Transaction* 0x48503d0 isEmpty=0 isCommitted=1>
`   <cling::Transaction* 0x4a10140 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x4a1d670 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x4a35200 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x5169f30 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x4a53570 isEmpty=0 isCommitted=1>
[cling]$ .undo
[cling]$ .stats undo
<cling::Transaction* 0x48503d0 isEmpty=0 isCommitted=1>
`   <cling::Transaction* 0x4a10140 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x4a1d670 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x4a35200 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x5169f30 isEmpty=0 isCommitted=1>
[cling]$ 1
(int) 1
```

As does eval/undo-2:

```
arch-vm[1085]:~% cling --nologo
[cling]$ .stats undo
<cling::Transaction* 0x3c6a3d0 isEmpty=0 isCommitted=1>
`   <cling::Transaction* 0x3e2a140 isEmpty=0 isCommitted=1>
[cling]$ 1
(int) 1
[cling]$ .stats undo
<cling::Transaction* 0x3c6a3d0 isEmpty=0 isCommitted=1>
`   <cling::Transaction* 0x3e2a140 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x3e37670 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x3e4ff50 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x4583f90 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x3e6d570 isEmpty=0 isCommitted=1>
[cling]$ .undo 2
[cling]$ .stats undo
<cling::Transaction* 0x3c6a3d0 isEmpty=0 isCommitted=1>
`   <cling::Transaction* 0x3e2a140 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x3e37670 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x3e4ff50 isEmpty=0 isCommitted=1>
[cling]$ 1
(int) 1
```

But undo-3 breaks:

```
arch-vm[1083]:~% cling --nologo
[cling]$ .stats undo
<cling::Transaction* 0x3c063d0 isEmpty=0 isCommitted=1>
`   <cling::Transaction* 0x3dc6140 isEmpty=0 isCommitted=1>
[cling]$ 1
(int) 1
[cling]$ .stats undo
<cling::Transaction* 0x3c063d0 isEmpty=0 isCommitted=1>
`   <cling::Transaction* 0x3dc6140 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x3dd3670 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x3debf50 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x451f0d0 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x3e09570 isEmpty=0 isCommitted=1>
[cling]$ .undo 3
[cling]$ 1
(int) ERROR in cling::executePrintValue(): cannot pass value!
ERROR in cling::executePrintValue(): missing value string.
[cling]$ .stats undo
<cling::Transaction* 0x3c063d0 isEmpty=0 isCommitted=1>
`   <cling::Transaction* 0x3dc6140 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x3dd3670 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x3debf50 isEmpty=0 isCommitted=1>
```

Evaluation is, again, broken at this point.
<hr />

### Undo and headers

```
arch-vm[1091]:~% cling --nologo
[cling]$ #include <functional>
[cling]$ .stats undo
<cling::Transaction* 0x3da73d0 isEmpty=0 isCommitted=1>
`   <cling::Transaction* 0x3f67140 isEmpty=0 isCommitted=1>
<cling::Transaction* 0x3f74670 isEmpty=0 isCommitted=1>
[cling]$ .undo
[cling]$ #include <functional>
In file included from input_line_4:1:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../include/c++/6.3.1/functional:53:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../include/c++/6.3.1/typeinfo:88:9: error: redefinition of 'type_info'
  class type_info
        ^
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../include/c++/6.3.1/typeinfo:88:9: note: previous definition is here
  class type_info
        ^
```
(rest snipped)

This doesn't seem to work even if you fool around with mixtures of `#include`, `.U`, `.L`, `.undo`, etc.

**Comment by vgvassilev** [comment]
Can you retry. I think we have committed a protection against such cases.

**Comment by drvink** [comment]
Rebuild from master just now and all of these are still broken.

**Comment by drvink** [comment]
Ah, I think you meant to write that reply in #128.

**Comment by vgvassilev** [comment]
Honestly, I didn't meant to reply to #128 but I am glad the other was fixed ;) I will investigate this issue because IIRC we introduced a fix for it, too.

**Comment by vgvassilev** [comment]
This should be fixed now. Thanks for the report.
